- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic
#    groups:
#      - name: emea-vars
#        nodes:
#         - node
         
- nodeset:
    name: nafta-node
    nodes:
      - name: node2
        label: centos76
      - name:node3
        label: ubuntu-node
        
- nodeset:
    name: gate-node
    nodes:
      - name: node3
        label: centos76 

- job:
    name: copylogsjob
    run: playbooks/copylogs.yaml
    parent: base

- project:
    check_emea:
      jobs:
        - copylogsjob:
            nodeset: emea-node
    check_nafta:
      jobs:
        - copylogsjob:
            nodeset: nafta-node
